# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acd < Formula
  desc "Atomic commit daemon for git worktrees, multi-harness"
  homepage "https://github.com/KristjanPikhof/Auto-Commit-Daemon"
  version "2026-07-13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-07-13/acd_2026-07-13_darwin_amd64.tar.gz"
      sha256 "b2a9282c20d0408beb9d1e3e6a117035fcb72315e104a979469cf88a8972b418"

      define_method(:install) do
        bin.install "acd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-07-13/acd_2026-07-13_darwin_arm64.tar.gz"
      sha256 "11fe1d9891842fa9bdd4f27f311d260e0e6afab061fe3ae584ea0d7390905e5d"

      define_method(:install) do
        bin.install "acd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-07-13/acd_2026-07-13_linux_amd64.tar.gz"
      sha256 "2e40923bda76ef4769c8f13dda691461f8c0867a549897eb4188635232db9154"
      define_method(:install) do
        bin.install "acd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-07-13/acd_2026-07-13_linux_arm64.tar.gz"
      sha256 "ede07b39855914b0f6c3b9301c5f3fcd858b4941e5a504ede6644f2ebc6c58ed"
      define_method(:install) do
        bin.install "acd"
      end
    end
  end

  test do
    assert_match "acd version", shell_output("#{bin}/acd version")
  end
end
