# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acd < Formula
  desc "Atomic commit daemon for git worktrees, multi-harness"
  homepage "https://github.com/KristjanPikhof/Auto-Commit-Daemon"
  version "2026-09-02"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-09-02/acd_2026-09-02_darwin_amd64.tar.gz"
      sha256 "46034b319d52dcb8a73b41dad83ef3bc7555fae0bc7d654ceb92fd932ac666e8"

      define_method(:install) do
        bin.install "acd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-09-02/acd_2026-09-02_darwin_arm64.tar.gz"
      sha256 "d0bcc6888b3bb7d9af1e9361495d526278f424dd53dcca0e7a81b737b754f459"

      define_method(:install) do
        bin.install "acd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-09-02/acd_2026-09-02_linux_amd64.tar.gz"
      sha256 "c85fceda070f307ad1f52b582f1775302735bc057ef15fbd59c306758c6b40e1"
      define_method(:install) do
        bin.install "acd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KristjanPikhof/Auto-Commit-Daemon/releases/download/v2026-09-02/acd_2026-09-02_linux_arm64.tar.gz"
      sha256 "c02d30fe9709c99f21007c8201faaac1327ba1df4d8877852825e44cbff4e16a"
      define_method(:install) do
        bin.install "acd"
      end
    end
  end

  test do
    assert_match "acd version", shell_output("#{bin}/acd version")
  end
end
